[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@foundry-devops=lib/foundry-devops/src",
]
fs_permissions = [
    { access = "read", path = "./img/" },
    { access = "read", path = "./broadcast" },
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
